norms.md, team-contract.md
=> Jk team contract

norms.md
=> Jk fixed norms

package.json
=> name change on package.json

server/db/models/index.js
=> Added associations

package-lock.json, server/db/models/user.js
=> User Model: Added isAdmin, address, imageUrl

server/db/models/item.js
=> updating item model round 2

script/seed.js, server/api/index.js, server/api/items.js, server/db/models/index.js
=> updated and tested items routes

client/store/user.js, server/api/index.js, server/api/users.js, server/db/models/index.js
=> Nam user reducer

server/api/index.js, server/api/users.js, server/db/models/index.js
Connected order and item routers to index.js
=> Nam connecting routes to api index

server/api/users.js, server/db/models/index.js
Redid routes to include Order instead of Cart.
Through table of Order and Item called Order_Content can be used to view the items in that order.
=> Nam redoing associations

server/api/index.js, server/api/orders.js
=> created orders routes

client/components/auth-form.js, client/components/navbar.js, public/style.css, server/api/index.js, server/db/models/index.js
=> CSS Updates to AuthForm / Navbar

server/db/models/index.js, server/db/models/orders.js
=> Orders Model Creation

server/api/index.js
=> Update to API index

client/store/item.js
=> update item reducer

client/components/SingleItem.js, client/routes.js, client/store/index.js, client/store/singleItem.js, public/style.css
=> WIP - Updates to Single Item View

client/components/AllItems.js, client/components/user-home.js, public/style.css
=> update all items component

client/components/AllItems.js
Hey Gang, I removed all delete functionality from this component. Thanks!
=> Bf all items component

server/db/models/user.js
=> Updated user model

client/components/SingleItem.js, client/components/index.js, server/db/models/item.js, server/db/models/order.js, server/db/models/orderContent.js
=> Update to naming conventions

server/api/orders.js
=> committing route orders

server/db/models/item.js, server/db/models/order.js, server/db/models/user.js
=> Model Updates

client/components/AllItems.js, client/components/UserHome.js, client/components/navbar.js, client/routes.js, client/store/index.js, client/store/item.js, public/style.css, script/seed.js, server/db/models/item.js
=> Updates to AllItems View

client/components/AllItems.js, client/routes.js, client/store/item.js, server/api/items.js
=> Updates to AllItems Component

client/store/user.js, server/auth/google.js
=> Update to Login Redirect

client/components/AllItems.js, client/components/SingleItem.js, public/index.html, public/style.css
=> Updates to Single Item View functionality

client/components/AllItems.js, client/components/SingleItem.js, package-lock.json, package.json, public/style.css
=> Update to AllItems

client/components/SingleItem.js, client/store/order.js, public/style.css, server/api/orders.js, server/db/models/orderContent.js
=> WIP - Updates to Add to Cart functionality

.travis.yml, client/components/AuthForm.js
=> Heroku deployment

client/components/UserHome.js
=> test with homepage. change from welcome, to welcome!

.travis.yml
=> create grace-shopper-test db on travis file

.travis.yml, package.json
=> Heroku db test

.travis.yml
=> added test on travis file

client/components/UserHome.js
=> test changed welcome on userhome

client/components/AuthForm.js, public/style.css, server/db/models/user.js
=> update sign up form functionality and form css

client/components/UserHome.js, server/api/users.js, server/app/secureMiddleware.js
=> add secure middleware to user routes

client/components/AllItems.js, client/components/Item.js, client/components/SingleItem.js, client/components/cart.js, client/store/order.js, client/store/singleItem.js, script/seed.js, server/api/items.js, server/api/orders.js, server/db/models/index.js, server/db/models/item.js, server/db/models/order.js, server/db/models/orderContent.js
=> Add to Cart functionality

client/components/Item.js
=> work on format price function

client/components/SingleItem.js, client/components/cart.js, client/store/order.js
=> Updates to Cart

server/api/items.js, server/api/orders.js
=> update secure middleware to work on all routes

client/components/CartItem.js, client/components/SingleItem.js, client/components/cart.js, client/routes.js, package-lock.json, public/style.css
=> Cart Component Data update

server/api/items.js, server/api/items.spec.js, server/api/orders.js
=> Bf secure middleware update

client/components/profile.js
=> Update to Profile page

client/components/AllUsers.js, client/components/EditAccountInfoForm.js, client/components/UserHome.js, client/components/navbar.js, client/routes.js, client/store/user.js, public/style.css, server/api/users.js
=> Admin functionality

client/components/SingleItem.js
=> fixed localstorage

client/components/UserHome.js, client/components/navbar.js, client/routes.js
=> fixed issues where guest can navigate the same as user

client/components/SingleItem.js, client/components/UserHome.js, client/components/navbar.js, public/style.css, script/seed.js, server/api/items.js, server/api/items.spec.js
=> Bf userhome component

client/components/AllUsers.js, client/components/AuthForm.js, client/components/CartItem.js, client/components/SingleItem.js, client/components/UserHome.js, client/components/cart.js, client/store/item.js, client/store/order.js, client/store/singleItem.js, client/store/user.js, server/api/items.js, server/api/orders.js, server/api/users.js, server/db/models/index.js, server/db/models/item.js, server/db/models/order.js, server/db/models/orderContent.js
=> Jenna cart functionality

client/components/cart.js, public/index.html, public/style.css, server/api/items.spec.js
=> once again adding item.spec.js to our repo

client/components/cart.js
=> guest cart obj

client/components/GuestCart.js, client/components/OrderConfirmation.js, client/components/SingleItem.js, client/components/navbar.js, client/routes.js
=> Guest Checkout functionality
